services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth

  pulsar:
    image: apachepulsar/pulsar:latest
    ports:
      - 6650:6650
    command: /pulsar/bin/pulsar standalone

  dashboard:
    image: apachepulsar/pulsar-manager:latest
    ports:
      - '9527:9527'
      - '7750:7750'
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
      PULSAR_MANAGER_OPTS: "-Dspring.datasource.initialization-mode=always"
    command: >
      sh -c "bin/pulsar-manager --redirect.host=http://localhost --redirect.port=9527 &
      sleep 10 &&
      CSRF_TOKEN=$$(curl -s http://localhost:7750/pulsar-manager/csrf-token) &&
      curl -s -H 'X-XSRF-TOKEN: '$$CSRF_TOKEN \
           -H 'Cookie: XSRF-TOKEN='$$CSRF_TOKEN \
           -H 'Content-Type: application/json' \
           -X PUT http://localhost:7750/pulsar-manager/users/superuser \
           -d '{\"name\":\"admin\",\"password\":\"apachepulsar\",\"description\":\"Default admin user\",\"email\":\"admin@pulsar.apache.org\"}' &&
      echo 'Created default admin user - Username: admin, Password: apachepulsar' &&
      tail -f /dev/null"
