name: 'E2E Test Setup'
description: 'Sets up environment for E2E testing with database and dependencies'

inputs:
  cache-key:
    description: 'Cache key for node_modules'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Start Docker Compose services
      shell: bash
      run: docker compose up -d

    - name: Wait for PostgreSQL
      shell: bash
      run: |
        timeout 30 bash -c 'until docker compose exec -T postgres pg_isready -U postgres; do sleep 1; done'

    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'yarn'

    - name: Restore node_modules
      uses: actions/cache/restore@v4
      with:
        path: |
          node_modules
          .yarn/cache
        key: ${{ inputs.cache-key }}
        fail-on-cache-miss: true

    - name: Restore Nx cache
      uses: actions/cache/restore@v4
      with:
        path: .nx/cache
        key: ${{ runner.os }}-nx-${{ hashFiles('nx.json', 'package.json', '**/project.json') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-nx-${{ hashFiles('nx.json', 'package.json', '**/project.json') }}-
          ${{ runner.os }}-nx-

    - name: Copy environment file
      shell: bash
      run: cp .env.sample .env

    - name: Run database migrations
      shell: bash
      run: yarn nx migrate-prisma auth-db
      env:
        DATABASE_URL: postgres://postgres:admin@localhost:5432/auth
