name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: auth
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - run: cp .env.sample .env

      - run: yarn install --immutable

      # Run Prisma migrations
      - name: Run database migrations
        run: yarn nx migrate-prisma auth-db
        env:
          DATABASE_URL: postgres://postgres:admin@localhost:5432/auth

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: yarn nx-cloud record -- echo Hello World
      - run: yarn nx run-many -t lint test build
        env:
          DATABASE_URL: postgres://postgres:admin@localhost:5432/auth
